<?php

require_once(TKT_APP.'/app.class.php');
require_once(TKT_ACTIONS.'/action.class.php');
require_once(TKT_FILTERS.'/filter.class.php');
require_once(TKT_SHORTCODES.'/shortcode.class.php');
require_once(TKT_SHORTCODES.'/program.class.php');
require_once(TKT_TEMPLATES.'/template.class.php');
require_once(TKT_HELPERS.'/utils.inc.php');
require_once(TKT_LIB.'/base/api.class.php');
require_once(TKT_LIB.'/base/money.class.php');
require_once(TKT_LIB.'/base/chf.class.php');
require_once(TKT_LIB.'/base/http.class.php');
require_once(TKT_LIB.'/base/model.class.php');
require_once(TKT_LIB.'/base/request.class.php');
require_once(TKT_LIB.'/models/bucket.class.php');
require_once(TKT_LIB.'/models/event.class.php');
require_once(TKT_LIB.'/models/movie.class.php');
require_once(TKT_LIB.'/models/place.class.php');
require_once(TKT_LIB.'/models/pricing.class.php');
require_once(TKT_LIB.'/models/screening.class.php');
require_once(TKT_LIB.'/models/tickettype.class.php');
require_once(TKT_LIB.'/models/window.class.php');
